using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoNex.Migrations
{
    /// <inheritdoc />
    public partial class AddToolCategoryEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS tool_categories (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    name character varying(100) NOT NULL,
                    is_deleted boolean NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_tool_categories"" PRIMARY KEY (""Id"")
                );

                INSERT INTO tool_categories (name, is_deleted, created_at, updated_at)
                SELECT 'Other', false, now(), now()
                WHERE NOT EXISTS (SELECT 1 FROM tool_categories WHERE name = 'Other');
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'tools' AND column_name = 'tool_category_id'
                    ) THEN
                        ALTER TABLE tools ADD COLUMN tool_category_id integer NOT NULL DEFAULT 1;
                        UPDATE tools SET tool_category_id = 1;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'tools' AND column_name = 'category'
                    ) THEN
                        ALTER TABLE tools DROP COLUMN category;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS IX_tools_tool_category_id ON tools (tool_category_id);");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints
                        WHERE constraint_name = 'FK_tools_tool_categories_tool_category_id'
                    ) THEN
                        ALTER TABLE tools ADD CONSTRAINT ""FK_tools_tool_categories_tool_category_id""
                            FOREIGN KEY (tool_category_id) REFERENCES tool_categories (""Id"") ON DELETE RESTRICT;
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE tools DROP CONSTRAINT IF EXISTS ""FK_tools_tool_categories_tool_category_id"";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS tool_categories;");
            migrationBuilder.Sql("DROP INDEX IF EXISTS IX_tools_tool_category_id;");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'tools' AND column_name = 'tool_category_id'
                    ) THEN
                        ALTER TABLE tools DROP COLUMN tool_category_id;
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'tools' AND column_name = 'category'
                    ) THEN
                        ALTER TABLE tools ADD COLUMN category character varying(50) NOT NULL DEFAULT '';
                    END IF;
                END $$;
            ");
        }
    }
}
